// Game Data with Multi-language Support
import { 
    Globe, Search, Briefcase, Smile, Camera, 
    Coffee, Music, ShoppingCart, Book, Star,
    Home, Pizza, Github, MapPin, Car, Trophy, Flag, Palette, GraduationCap, Laptop, Film, Cloud, Tag, Shield, Gamepad2, User, Activity, Microscope
} from 'lucide-react';

export const CATEGORIES = [
  { 
    id: 'daily', 
    name: { az: 'Gündəlik', tr: 'Günlük', en: 'Daily', ru: 'Ежедневно' },
    icon: Home, 
    color: 'from-blue-500 to-cyan-500', 
    words: {
        az: ['Açar', 'Pulqabı', 'Telefon', 'Saat', 'Eynək', 'Çanta', 'Dəftər', 'Sabun', 'Daraq', 'Güzgü', 'Çətir', 'Qələm', 'Lampa', 'Masa', 'Kreslo', 'Yataq', 'Yastıq', 'Xalça', 'Pərdə', 'Qapı', 'Pəncərə', 'Soyuducu', 'Ütü', 'Televizor', 'Fincan', 'Qaşıq', 'Çəngəl', 'Bıçaq', 'Boşqab', 'Salfetka', 'Çaydan', 'Şüşə', 'Kəmər', 'Papaq', 'Şərf', 'Əlcək', 'Corab', 'Ayaqqabı', 'Köynək', 'Şalvar', 'Gödəkcə', 'Düymə', 'Zibil Qabı', 'Kibrit', 'Şam', 'Batareya', 'Qulaqlıq', 'Adapter', 'Yorğan', 'Döşək'],
        tr: ['Anahtar', 'Cüzdan', 'Telefon', 'Saat', 'Gözlük', 'Çanta', 'Defter', 'Sabun', 'Tarak', 'Ayna', 'Şemsiye', 'Kalem', 'Lamba', 'Masa', 'Koltuk', 'Yatak', 'Yastık', 'Halı', 'Perde', 'Kapı', 'Pencere', 'Buzdolabı', 'Ütü', 'Televizyon', 'Fincan', 'Kaşık', 'Çatal', 'Bıçak', 'Tabak', 'Peçete', 'Çaydanlık', 'Şişe', 'Kemer', 'Şapka', 'Atkı', 'Eldiven', 'Çorap', 'Ayakkabı', 'Gömlek', 'Pantolon', 'Ceket', 'Düğme', 'Çöp Kutusu', 'Kibrit', 'Mum', 'Pil', 'Kulaklık', 'Adaptör', 'Yorgan', 'Şilte'],
        en: ['Key', 'Wallet', 'Phone', 'Watch', 'Glasses', 'Bag', 'Notebook', 'Soap', 'Comb', 'Mirror', 'Umbrella', 'Pen', 'Lamp', 'Table', 'Armchair', 'Bed', 'Pillow', 'Carpet', 'Curtain', 'Door', 'Window', 'Fridge', 'Iron', 'TV', 'Cup', 'Spoon', 'Fork', 'Knife', 'Plate', 'Napkin', 'Teapot', 'Bottle', 'Belt', 'Hat', 'Scarf', 'Gloves', 'Socks', 'Shoes', 'Shirt', 'Trousers', 'Jacket', 'Button', 'Trash Can', 'Match', 'Candle', 'Battery', 'Headphones', 'Adapter', 'Blanket', 'Mattress'],
        ru: ['Ключ', 'Кошелек', 'Телефон', 'Часы', 'Очки', 'Сумка', 'Тетрадь', 'Мыло', 'Расческа', 'Зеркало', 'Зонт', 'Ручка', 'Лампа', 'Стол', 'Кресло', 'Кровать', 'Подушка', 'Ковер', 'Занавеска', 'Дверь', 'Окно', 'Холодильник', 'Утюг', 'Телевизор', 'Чашка', 'Ложка', 'Вилка', 'Нож', 'Тарелка', 'Салфетка', 'Чайник', 'Бутылка', 'Ремень', 'Шапка', 'Шарф', 'Перчатки', 'Носки', 'Обувь', 'Рубашка', 'Брюки', 'Куртка', 'Пуговица', 'Мусорка', 'Спички', 'Свеча', 'Батарейка', 'Наушники', 'Адаптер', 'Одеяло', 'Матрас']
    }
  },
  { 
    id: 'food', 
    name: { az: 'Yemək', tr: 'Yiyecek', en: 'Food', ru: 'Еда' },
    icon: Pizza, 
    color: 'from-orange-500 to-red-500', 
    words: {
        az: ['Pizza', 'Suşi', 'Burger', 'Dönər', 'Kabab', 'Dolma', 'Plov', 'Şorba', 'Salat', 'Makaron', 'Toyuq', 'Balıq', 'Kartof', 'Pomidor', 'Xiyar', 'Soğan', 'Sarımsaq', 'Kök', 'Bibər', 'Badımcan', 'Alma', 'Armud', 'Banan', 'Üzüm', 'Qarpız', 'Yemiş', 'Çiyələk', 'Gilas', 'Limon', 'Portağal', 'Naringi', 'Nar', 'Çörək', 'Pendir', 'Yağ', 'Yumurta', 'Süd', 'Qatıq', 'Düyü', 'Mərcimək', 'Noxud', 'Fındıq', 'Qoz', 'Badam', 'Şokolad', 'Dondurma', 'Tort', 'Keks', 'Paxlava', 'Şəkərbura', 'Qutab'],
        tr: ['Pizza', 'Suşi', 'Burger', 'Döner', 'Kebap', 'Dolma', 'Pilav', 'Çorba', 'Salata', 'Makarna', 'Tavuk', 'Balık', 'Patates', 'Domates', 'Salatalık', 'Soğan', 'Sarımsak', 'Havuç', 'Biber', 'Patlıcan', 'Elma', 'Armut', 'Muz', 'Üzüm', 'Karpuz', 'Kavun', 'Çilek', 'Kiraz', 'Limon', 'Portakal', 'Mandalina', 'Nar', 'Ekmek', 'Peynir', 'Yağ', 'Yumurta', 'Süt', 'Yoğurt', 'Pirinç', 'Mercimek', 'Nohut', 'Fındık', 'Ceviz', 'Badem', 'Çikolata', 'Dondurma', 'Pasta', 'Kek', 'Baklava', 'Şekerpare', 'Gözleme'],
        en: ['Pizza', 'Sushi', 'Burger', 'Doner', 'Kebab', 'Dolma', 'Pilaf', 'Soup', 'Salad', 'Pasta', 'Chicken', 'Fish', 'Potato', 'Tomato', 'Cucumber', 'Onion', 'Garlic', 'Carrot', 'Pepper', 'Eggplant', 'Apple', 'Pear', 'Banana', 'Grape', 'Watermelon', 'Melon', 'Strawberry', 'Cherry', 'Lemon', 'Orange', 'Tangerine', 'Pomegranate', 'Bread', 'Cheese', 'Butter', 'Egg', 'Milk', 'Yogurt', 'Rice', 'Lentil', 'Chickpeas', 'Hazelnut', 'Walnut', 'Almond', 'Chocolate', 'Ice Cream', 'Cake', 'Cupcake', 'Baklava', 'Cookie', 'Pancake'],
        ru: ['Пицца', 'Суши', 'Бургер', 'Донер', 'Кебаб', 'Долма', 'Плов', 'Суп', 'Салат', 'Макароны', 'Курица', 'Рыба', 'Картофель', 'Помидор', 'Огурец', 'Лук', 'Чеснок', 'Морковь', 'Перец', 'Баклажан', 'Яблоко', 'Груша', 'Банан', 'Виноград', 'Арбуз', 'Дыня', 'Клубника', 'Вишня', 'Лимон', 'Апельсин', 'Мандарин', 'Гранат', 'Хлеб', 'Сыр', 'Масло', 'Яйцо', 'Молоко', 'Йогурт', 'Рис', 'Чечевица', 'Нут', 'Фундук', 'Грецкий орех', 'Миндаль', 'Шоколад', 'Мороженое', 'Торт', 'Кекс', 'Пахлава', 'Печенье', 'Блин']
    }
  },
  { 
    id: 'animals', 
    name: { az: 'Heyvanlar', tr: 'Hayvanlar', en: 'Animals', ru: 'Животные' },
    icon: Github, 
    color: 'from-green-500 to-emerald-500', 
    words: {
        az: ['Şir', 'Pələng', 'Pişik', 'İt', 'At', 'Qartal', 'İlan', 'Balıq', 'Ayı', 'Canavar', 'Tülkü', 'Dovşan', 'Siçan', 'Kirpi', 'Sincab', 'Meymun', 'Zürafə', 'Fil', 'Kərgədan', 'Begemot', 'Timsah', 'Qurbağa', 'Tısbağa', 'Kərtənkələ', 'Yarasa', 'Bayquş', 'Qarğa', 'Göyərçin', 'Sərçə', 'Qaranquş', 'Tovuzquşu', 'Pinqvin', 'Delfin', 'Köpəkbalığı', 'Balina', 'Osminoq', 'Meduza', 'Xərçəng', 'Hörümçək', 'Arı', 'Qarışqa', 'Kəpənək', 'Milçək', 'Ağcaqanad', 'İnək', 'Qoyun', 'Keçi', 'Toyuq', 'Xoruz', 'Ördək', 'Qaz'],
        tr: ['Aslan', 'Kaplan', 'Kedi', 'Köpek', 'At', 'Kartal', 'Yılan', 'Balık', 'Ayı', 'Kurt', 'Tilki', 'Tavşan', 'Fare', 'Kirpi', 'Sincap', 'Maymun', 'Zürafa', 'Fil', 'Gergedan', 'Su Aygırı', 'Timsah', 'Kurbağa', 'Kaplumbağa', 'Kertenkele', 'Yarasa', 'Baykuş', 'Karga', 'Güvercin', 'Serçe', 'Kırlangıç', 'Tavuskuşu', 'Penguen', 'Yunus', 'Köpekbalığı', 'Balina', 'Ahtapot', 'Denizanası', 'Yengeç', 'Örümcek', 'Arı', 'Karınca', 'Kelebek', 'Sinek', 'Sivrisinek', 'İnek', 'Koyun', 'Keçi', 'Tavuk', 'Horoz', 'Ördek', 'Kaz'],
        en: ['Lion', 'Tiger', 'Cat', 'Dog', 'Horse', 'Eagle', 'Snake', 'Fish', 'Bear', 'Wolf', 'Fox', 'Rabbit', 'Mouse', 'Hedgehog', 'Squirrel', 'Monkey', 'Giraffe', 'Elephant', 'Rhino', 'Hippo', 'Crocodile', 'Frog', 'Turtle', 'Lizard', 'Bat', 'Owl', 'Crow', 'Pigeon', 'Sparrow', 'Swallow', 'Peacock', 'Penguin', 'Dolphin', 'Shark', 'Whale', 'Octopus', 'Jellyfish', 'Crab', 'Spider', 'Bee', 'Ant', 'Butterfly', 'Fly', 'Mosquito', 'Cow', 'Sheep', 'Goat', 'Chicken', 'Rooster', 'Duck', 'Goose'],
        ru: ['Лев', 'Тигр', 'Кошка', 'Собака', 'Лошадь', 'Орел', 'Змея', 'Рыба', 'Медведь', 'Волк', 'Лиса', 'Кролик', 'Мышь', 'Еж', 'Белка', 'Обезьяна', 'Жираф', 'Слон', 'Носорог', 'Бегемот', 'Крокодил', 'Лягушка', 'Черепаха', 'Ящерица', 'Летучая мышь', 'Сова', 'Ворона', 'Голубь', 'Воробей', 'Ласточка', 'Павлин', 'Пингвин', 'Дельфин', 'Акула', 'Кит', 'Осьминог', 'Медуза', 'Краб', 'Паук', 'Пчела', 'Муравей', 'Бабочка', 'Муха', 'Комар', 'Корова', 'Овца', 'Коза', 'Курица', 'Петух', 'Утка', 'Гусь']
    }
  },
  { 
    id: 'job', 
    name: { az: 'Peşələr', tr: 'Meslekler', en: 'Professions', ru: 'Профессии' },
    icon: Briefcase, 
    color: 'from-purple-500 to-pink-500', 
    words: { 
        az: ['Həkim', 'Müəllim', 'Mühəndis', 'Polis', 'Yanğınsöndürən', 'Aşpaz', 'Bərbər', 'Sürücü', 'Pilot', 'Kapitan', 'Əsgər', 'Rəssam', 'Musiqiçi', 'Aktyor', 'Müğənni', 'Yazıçı', 'Jurnalist', 'Proqramçı', 'Dizayner', 'Memar', 'Fəhlə', 'Elektrik', 'Santexnik', 'Dülgər', 'Dərzi', 'Satıcı', 'Kassir', 'Bankir', 'Vəkil', 'Hakim', 'Prokuror', 'Poçtalyon', 'Fermer', 'Bağban', 'Baytar', 'Diş Həkimi', 'Cərrah', 'Tibb Bacısı', 'Psixoloq', 'Alim', 'Astronom', 'Tarixçi', 'Tərcüməçi', 'Fotoqraf', 'Rejissor', 'İdmançı', 'Məşqçi', 'Hakim (İdman)', 'Prezident', 'Nazir'],
        tr: ['Doktor', 'Öğretmen', 'Mühendis', 'Polis', 'İtfaiyeci', 'Aşçı', 'Berber', 'Şoför', 'Pilot', 'Kaptan', 'Asker', 'Ressam', 'Müzisyen', 'Oyuncu', 'Şarkıcı', 'Yazar', 'Gazeteci', 'Yazılımcı', 'Tasarımcı', 'Mimar', 'İşçi', 'Elektrikçi', 'Tesisatçı', 'Marangoz', 'Terzi', 'Satıcı', 'Kasiyer', 'Bankacı', 'Avukat', 'Hakim', 'Savcı', 'Postacı', 'Çiftçi', 'Bahçıvan', 'Veteriner', 'Diş Hekimi', 'Cerrah', 'Hemşire', 'Psikolog', 'Bilim İnsanı', 'Astronom', 'Tarihçi', 'Tercüman', 'Fotoğrafçı', 'Yönetmen', 'Sporcu', 'Antrenör', 'Hakem', 'Başkan', 'Bakan'],
        en: ['Doctor', 'Teacher', 'Engineer', 'Police', 'Firefighter', 'Chef', 'Barber', 'Driver', 'Pilot', 'Captain', 'Soldier', 'Artist', 'Musician', 'Actor', 'Singer', 'Writer', 'Journalist', 'Programmer', 'Designer', 'Architect', 'Worker', 'Electrician', 'Plumber', 'Carpenter', 'Tailor', 'Seller', 'Cashier', 'Banker', 'Lawyer', 'Judge', 'Prosecutor', 'Postman', 'Farmer', 'Gardener', 'Vet', 'Dentist', 'Surgeon', 'Nurse', 'Psychologist', 'Scientist', 'Astronomer', 'Historian', 'Translator', 'Photographer', 'Director', 'Athlete', 'Coach', 'Referee', 'President', 'Minister'],
        ru: ['Врач', 'Учитель', 'Инженер', 'Полицейский', 'Пожарный', 'Повар', 'Парикмахер', 'Водитель', 'Пилот', 'Капитан', 'Солдат', 'Художник', 'Музыкант', 'Актер', 'Певец', 'Писатель', 'Журналист', 'Программист', 'Дизайнер', 'Архитектор', 'Рабочий', 'Электрик', 'Сантехник', 'Плотник', 'Портной', 'Продавец', 'Кассир', 'Банкир', 'Юрист', 'Судья', 'Прокурор', 'Почтальон', 'Фермер', 'Садовник', 'Ветеринар', 'Стоматолог', 'Хирург', 'Медсестра', 'Психолог', 'Ученый', 'Астроном', 'Историк', 'Переводчик', 'Фотограф', 'Режиссер', 'Спортсмен', 'Тренер', 'Рефери', 'Президент', 'Министр']
    }
  },
  { 
    id: 'places', 
    name: { az: 'Məkanlar', tr: 'Mekanlar', en: 'Places', ru: 'Места' },
    icon: MapPin, 
    color: 'from-yellow-500 to-orange-500', 
    words: {
        az: ['Park', 'Məktəb', 'Xəstəxana', 'Restoran', 'Kinoteatr', 'Muzey', 'Teatr', 'Kitabxana', 'Stadion', 'Hovuz', 'İdman Zalı', 'Mağaza', 'Bazar', 'Aptek', 'Bank', 'Poçt', 'Polis Bölməsi', 'Yanğın Hissəsi', 'Hava Limanı', 'Vağzal', 'Liman', 'Otel', 'Ev', 'Mənzil', 'Bağ', 'Meşə', 'Dağ', 'Dəniz', 'Göl', 'Çay', 'Şəlalə', 'Mağara', 'Səhra', 'Ada', 'Kənd', 'Şəhər', 'Ölkə', 'Qitə', 'Planet', 'Kosmos', 'Məscid', 'Kilsə', 'Saray', 'Qala', 'Körpü', 'Tunel', 'Yol', 'Küçə', 'Meydan', 'Zoopark'],
        tr: ['Park', 'Okul', 'Hastane', 'Restoran', 'Sinema', 'Müze', 'Tiyatro', 'Kütüphane', 'Stadyum', 'Havuz', 'Spor Salonu', 'Mağaza', 'Pazar', 'Eczane', 'Banka', 'Postane', 'Polis Merkezi', 'İtfaiye', 'Havalimanı', 'Gar', 'Liman', 'Otel', 'Ev', 'Daire', 'Bahçe', 'Orman', 'Dağ', 'Deniz', 'Göl', 'Nehir', 'Şelale', 'Mağara', 'Çöl', 'Ada', 'Köy', 'Şehir', 'Ülke', 'Kıta', 'Gezegen', 'Uzay', 'Cami', 'Kilise', 'Saray', 'Kale', 'Köprü', 'Tünel', 'Yol', 'Sokak', 'Meydan', 'Hayvanat Bahçesi'],
        en: ['Park', 'School', 'Hospital', 'Restaurant', 'Cinema', 'Museum', 'Theater', 'Library', 'Stadium', 'Pool', 'Gym', 'Shop', 'Market', 'Pharmacy', 'Bank', 'Post Office', 'Police Station', 'Fire Station', 'Airport', 'Station', 'Port', 'Hotel', 'House', 'Apartment', 'Garden', 'Forest', 'Mountain', 'Sea', 'Lake', 'River', 'Waterfall', 'Cave', 'Desert', 'Island', 'Village', 'City', 'Country', 'Continent', 'Planet', 'Space', 'Mosque', 'Church', 'Palace', 'Castle', 'Bridge', 'Tunnel', 'Road', 'Street', 'Square', 'Zoo'],
        ru: ['Парк', 'Школа', 'Больница', 'Ресторан', 'Кинотеатр', 'Музей', 'Театр', 'Библиотека', 'Стадион', 'Бассейн', 'Спортзал', 'Магазин', 'Рынок', 'Аптека', 'Банк', 'Почта', 'Полиция', 'Пожарная', 'Аэропорт', 'Вокзал', 'Порт', 'Отель', 'Дом', 'Квартира', 'Сад', 'Лес', 'Гора', 'Море', 'Озеро', 'Река', 'Водопад', 'Пещера', 'Пустыня', 'Остров', 'Деревня', 'Город', 'Страна', 'Континент', 'Планета', 'Космос', 'Мечеть', 'Церковь', 'Дворец', 'Замок', 'Мост', 'Тоннель', 'Дорога', 'Улица', 'Площадь', 'Зоопарк']
    }
  },
  { 
    id: 'transport', 
    name: { az: 'Nəqliyyat', tr: 'Ulaşım', en: 'Transport', ru: 'Транспорт' },
    icon: Car, 
    color: 'from-red-500 to-pink-500', 
    words: {
        az: ['Avtomobil', 'Avtobus', 'Qatar', 'Təyyarə', 'Gəmi', 'Velosiped', 'Motosiklet', 'Skuter', 'Taksi', 'Metro', 'Tramvay', 'Trolleybus', 'Yük maşını (Kamaz)', 'Traktor', 'Ekskavator', 'Kran', 'Təcili Yardım', 'Polis Maşını', 'Yanğınsöndürən', 'Qayıq', 'Yat', 'Kater', 'Bərə', 'Sualtı Qayıq', 'Helikopter', 'Raket', 'Kosmik Gəmi', 'Paraşüt', 'Dirijabl (Hava şarı)', 'Fayton', 'At Arabası', 'Xizək', 'Skeytbord', 'Paten', 'Lift', 'Eskalator', 'Kanat', 'Funikulyor', 'Tank', 'Zirehli Maşın', 'Limuzin', 'Jeep', 'Minivan', 'Pikap', 'Furqon', 'TIR', 'Trayler', 'Qolf Arabası', 'Segway'],
        tr: ['Araba', 'Otobüs', 'Tren', 'Uçak', 'Gemi', 'Bisiklet', 'Motosiklet', 'Scooter', 'Taksi', 'Metro', 'Tramvay', 'Metrobüs', 'Kamyon', 'Traktör', 'Kepçe', 'Vinç', 'Ambulans', 'Polis Aracı', 'İtfaiye', 'Kayık', 'Yat', 'Tekne', 'Feribot', 'Denizaltı', 'Helikopter', 'Roket', 'Uzay Gemisi', 'Paraşüt', 'Zeplin', 'Fayton', 'At Arabası', 'Kızak', 'Kaykay', 'Paten', 'Asansör', 'Yürüyen Merdiven', 'Teleferik', 'Füniküler', 'Tank', 'Zırhlı Araç', 'Limuzin', 'Jeep', 'Minibüs', 'Kamyonet', 'Panelvan', 'TIR', 'Karavan', 'Golf Arabası', 'Segway'],
        en: ['Car', 'Bus', 'Train', 'Plane', 'Ship', 'Bicycle', 'Motorcycle', 'Scooter', 'Taxi', 'Subway', 'Tram', 'Trolleybus', 'Truck', 'Tractor', 'Excavator', 'Crane', 'Ambulance', 'Police Car', 'Fire Truck', 'Boat', 'Yacht', 'Speedboat', 'Ferry', 'Submarine', 'Helicopter', 'Rocket', 'Spaceship', 'Parachute', 'Blimp', 'Carriage', 'Cart', 'Sled', 'Skateboard', 'Skates', 'Elevator', 'Escalator', 'Cable Car', 'Funicular', 'Tank', 'Armored Car', 'Limousine', 'Jeep', 'Minivan', 'Pickup', 'Van', 'Trailer', 'RV', 'Golf Cart', 'Segway'],
        ru: ['Машина', 'Автобус', 'Поезд', 'Самолет', 'Корабль', 'Велосипед', 'Мотоцикл', 'Скутер', 'Такси', 'Метро', 'Трамвай', 'Троллейбус', 'Грузовик', 'Трактор', 'Экскаватор', 'Кран', 'Скорая Помощь', 'Полицейская Машина', 'Пожарная Машина', 'Лодка', 'Яхта', 'Катер', 'Паром', 'Подводная Лодка', 'Вертолет', 'Ракета', 'Космический Корабль', 'Парашют', 'Дирижабль', 'Фаэтон', 'Повозка', 'Сани', 'Скейтборд', 'Ролики', 'Лифт', 'Эскалатор', 'Канатная Дорога', 'Фуникулер', 'Танк', 'Бронемашина', 'Лимузин', 'Джип', 'Минивэн', 'Пикап', 'Фургон', 'Фура', 'Трейлер', 'Гольф-кар', 'Сегвей']
    }
  },
   { id: 'sports', name: { az: 'İdman', tr: 'Spor', en: 'Sports', ru: 'Спорт' }, icon: Trophy, color: 'from-indigo-500 to-blue-500', words: {
       az: ['Futbol', 'Basketbol', 'Voleybol', 'Tennis', 'Üzgüçülük', 'Boks', 'Güləş', 'Cüdo', 'Karate', 'Şahmat', 'Qolf', 'Reqbi', 'Xokkey', 'Buzüstü', 'Xizək', 'Atletika', 'Qaçış', 'Velosiped', 'Avarçəkmə', 'Gimnastika', 'Ağırlıqqaldırma', 'Badminton', 'Stolüstü Tennis', 'Bilyard', 'Bowling', 'Darts', 'Oxatma', 'Atıcılıq', 'Qılıncoynatma', 'Atçılıq', 'Sörfinq', 'Alpinizm', 'Yoga', 'Pilates', 'Krossfit', 'Sumo', 'Taekvondo', 'Kikboks', 'MMA', 'Formula 1', 'Ralli', 'Motokross', 'Snooker', 'Körlinq', 'Beysbol', 'Kriket', 'Amerika Futbolu', 'Həndbol'],
       tr: ['Futbol', 'Basketbol', 'Voleybol', 'Tenis', 'Yüzme', 'Boks', 'Güreş', 'Judo', 'Karate', 'Satranç', 'Golf', 'Ragbi', 'Hokey', 'Buz Pateni', 'Kayak', 'Atletizm', 'Koşu', 'Bisiklet', 'Kürek', 'Jimnastik', 'Halter', 'Badminton', 'Masa Tenisi', 'Bilardo', 'Bowling', 'Dart', 'Okçuluk', 'Atıcılık', 'Eskrim', 'Binicilik', 'Sörf', 'Dağcılık', 'Yoga', 'Pilates', 'Crossfit', 'Sumo', 'Tekvando', 'Kickboks', 'MMA', 'Formula 1', 'Ralli', 'Motokros', 'Snooker', 'Curling', 'Beyzbol', 'Kriket', 'Amerikan Futbolu', 'Hentbol'],
       en: ['Football', 'Basketball', 'Volleyball', 'Tennis', 'Swimming', 'Boxing', 'Wrestling', 'Judo', 'Karate', 'Chess', 'Golf', 'Rugby', 'Hockey', 'Ice Skating', 'Skiing', 'Athletics', 'Running', 'Cycling', 'Rowing', 'Gymnastics', 'Weightlifting', 'Badminton', 'Table Tennis', 'Billiards', 'Bowling', 'Darts', 'Archery', 'Shooting', 'Fencing', 'Horse Riding', 'Surfing', 'Climbing', 'Yoga', 'Pilates', 'Crossfit', 'Sumo', 'Taekwondo', 'Kickboxing', 'MMA', 'Formula 1', 'Rally', 'Motocross', 'Snooker', 'Curling', 'Baseball', 'Cricket', 'American Football', 'Handball'],
       ru: ['Футбол', 'Баскетбол', 'Волейбол', 'Теннис', 'Плавание', 'Бокс', 'Борьба', 'Дзюдо', 'Карате', 'Шахматы', 'Гольф', 'Регби', 'Хоккей', 'Фигурное Катание', 'Лыжи', 'Атлетика', 'Бег', 'Велоспорт', 'Гребля', 'Гимнастика', 'Тяжелая Атлетика', 'Бадминтон', 'Настольный Теннис', 'Бильярд', 'Боулинг', 'Дартс', 'Стрельба из лука', 'Стрельба', 'Фехтование', 'Верховая Езда', 'Серфинг', 'Альпинизм', 'Йога', 'Пилатес', 'Кроссфит', 'Сумо', 'Тхэквондо', 'Кикбоксинг', 'ММА', 'Формула 1', 'Ралли', 'Мотокросс', 'Снукер', 'Керлинг', 'Бейсбол', 'Крикет', 'Американский Футбол', 'Гандбол']
   }},
  { id: 'country', name: { az: 'Ölkələr', tr: 'Ülkeler', en: 'Countries', ru: 'Страны' }, icon: Flag, color: 'from-teal-500 to-green-500', words: {
      az: ['Azərbaycan', 'Türkiyə', 'Rusiya', 'ABŞ', 'Almaniya', 'Fransa', 'İtaliya', 'İspaniya', 'Böyük Britaniya', 'Çin', 'Yaponiya', 'Cənubi Koreya', 'Hindistan', 'Pakistan', 'İran', 'Gürcüstan', 'Ukrayna', 'Qazaxıstan', 'Özbəkistan', 'Türkmənistan', 'Qırğızıstan', 'Səudiyyə Ərəbistanı', 'BƏƏ', 'Misir', 'Mərakeş', 'Braziliya', 'Argentina', 'Kanada', 'Meksika', 'Avstraliya', 'Yeni Zelandiya', 'Yunanıstan', 'İsveçrə', 'İsveç', 'Norveç', 'Finlandiya', 'Danimarka', 'Niderland', 'Belçika', 'Portuqaliya', 'Polşa', 'Macarıstan', 'Çexiya', 'Avstriya', 'Serbiya', 'Xorvatiya', 'Bosniya', 'Albaniya', 'Monteneqro', 'Şimali Kipr'],
      tr: ['Azerbaycan', 'Türkiye', 'Rusya', 'ABD', 'Almanya', 'Fransa', 'İtalya', 'İspanya', 'Birleşik Krallık', 'Çin', 'Japonya', 'Güney Kore', 'Hindistan', 'Pakistan', 'İran', 'Gürcistan', 'Ukrayna', 'Kazakistan', 'Özbekistan', 'Türkmenistan', 'Kırgızistan', 'Suudi Arabistan', 'BAE', 'Mısır', 'Fas', 'Brezilya', 'Arjantin', 'Kanada', 'Meksika', 'Avustralya', 'Yeni Zelanda', 'Yunanistan', 'İsviçre', 'İsveç', 'Norveç', 'Finlandiya', 'Danimarka', 'Hollanda', 'Belçika', 'Portekiz', 'Polonya', 'Macaristan', 'Çekya', 'Avusturya', 'Sırbistan', 'Hırvatistan', 'Bosna', 'Arnavutluk', 'Karadağ', 'KKTC'],
      en: ['Azerbaijan', 'Turkey', 'Russia', 'USA', 'Germany', 'France', 'Italy', 'Spain', 'UK', 'China', 'Japan', 'South Korea', 'India', 'Pakistan', 'Iran', 'Georgia', 'Ukraine', 'Kazakhstan', 'Uzbekistan', 'Turkmenistan', 'Kyrgyzstan', 'Saudi Arabia', 'UAE', 'Egypt', 'Morocco', 'Brazil', 'Argentina', 'Canada', 'Mexico', 'Australia', 'New Zealand', 'Greece', 'Switzerland', 'Sweden', 'Norway', 'Finland', 'Denmark', 'Netherlands', 'Belgium', 'Portugal', 'Poland', 'Hungary', 'Czechia', 'Austria', 'Serbia', 'Croatia', 'Bosnia', 'Albania', 'Montenegro', 'Northern Cyprus'],
      ru: ['Азербайджан', 'Турция', 'Россия', 'США', 'Германия', 'Франция', 'Италия', 'Испания', 'Великобритания', 'Китай', 'Япония', 'Южная Корея', 'Индия', 'Пакистан', 'Иран', 'Грузия', 'Украина', 'Казахстан', 'Узбекистан', 'Туркменистан', 'Киргизия', 'Саудовская Аравия', 'ОАЭ', 'Египет', 'Марокко', 'Бразилия', 'Аргентина', 'Канада', 'Мексика', 'Австралия', 'Новая Зеландия', 'Греция', 'Швейцария', 'Швеция', 'Норвегия', 'Финляндия', 'Дания', 'Нидерланды', 'Бельгия', 'Португалия', 'Польша', 'Венгрия', 'Чехия', 'Австрия', 'Сербия', 'Хорватия', 'Босния', 'Албания', 'Черногория', 'Северный Кипр']
  }},
  { id: 'colors', name: { az: 'Rənglər', tr: 'Renkler', en: 'Colors', ru: 'Цвета' }, icon: Palette, color: 'from-pink-500 to-rose-500', words: {
      az: ['Qırmızı', 'Mavi', 'Yaşıl', 'Sarı', 'Qara', 'Ağ', 'Boz', 'Qəhvəyi', 'Narıncı', 'Bənövşəyi', 'Çəhrayı', 'Firuzəyi', 'Gümüşü', 'Qızılı', 'Tünd Göy', 'Açıq Mavi', 'Tünd Yaşıl', 'Açıq Yaşıl', 'Xaki', 'Bordo', 'Yasəmən', 'Bej', 'Krem', 'Mərcan', 'Zeytun', 'Şaftalı', 'Mint', 'Lavanda', 'İndiqo', 'Albalı', 'Kərpic', 'Oxra', 'Firuzəyi', 'Fuksiya', 'Metalik', 'Neon Yaşıl', 'Neon Çəhrayı', 'Qaranlıq', 'İşıqlı', 'Rəngarəng', 'Mat', 'Parlaq', 'Şəffaf', 'Ala-bəzək', 'Zolaqlı', 'Xallı', 'Qırmızımtıl', 'Sarımtıl', 'Göyümtül'],
      tr: ['Kırmızı', 'Mavi', 'Yeşil', 'Sarı', 'Siyah', 'Beyaz', 'Gri', 'Kahverengi', 'Turuncu', 'Mor', 'Pembe', 'Turkuaz', 'Gümüş', 'Altın', 'Lacivert', 'Açık Mavi', 'Koyu Yeşil', 'Açık Yeşil', 'Haki', 'Bordo', 'Lila', 'Bej', 'Krem', 'Mercan', 'Zeytin', 'Şeftali', 'Nane', 'Lavanta', 'Çivit', 'Vişne', 'Kiremit', 'Hardal', 'Camgöbeği', 'Macenta', 'Metalik', 'Neon Yeşil', 'Neon Pembe', 'Karanlık', 'Aydınlık', 'Renkli', 'Mat', 'Parlak', 'Şeffaf', 'Alaca', 'Çizgili', 'Benekli', 'Kırmızımsı', 'Sarımsı', 'Mavimsi'],
      en: ['Red', 'Blue', 'Green', 'Yellow', 'Black', 'White', 'Gray', 'Brown', 'Orange', 'Purple', 'Pink', 'Turquoise', 'Silver', 'Gold', 'Navy Blue', 'Light Blue', 'Dark Green', 'Light Green', 'Khaki', 'Burgundy', 'Lilac', 'Beige', 'Cream', 'Coral', 'Olive', 'Peach', 'Mint', 'Lavender', 'Indigo', 'Cherry', 'Brick', 'Ochre', 'Cyan', 'Magenta', 'Metallic', 'Neon Green', 'Neon Pink', 'Dark', 'Light', 'Colorful', 'Matte', 'Shiny', 'Transparent', 'Variegated', 'Striped', 'Spotted', 'Reddish', 'Yellowish', 'Bluish'],
      ru: ['Красный', 'Синий', 'Зеленый', 'Желтый', 'Черный', 'Белый', 'Серый', 'Коричневый', 'Оранжевый', 'Фиолетовый', 'Розовый', 'Бирюзовый', 'Серебряный', 'Золотой', 'Темно-синий', 'Голубой', 'Темно-зеленый', 'Светло-зеленый', 'Хаки', 'Бордовый', 'Сиреневый', 'Бежевый', 'Кремовый', 'Коралловый', 'Оливковый', 'Персиковый', 'Мятный', 'Лавандовый', 'Индиго', 'Вишневый', 'Кирпичный', 'Охра', 'Циан', 'Маджента', 'Металлик', 'Неоновый Зеленый', 'Неоновый Розовый', 'Темный', 'Светлый', 'Разноцветный', 'Матовый', 'Блестящий', 'Прозрачный', 'Пестрый', 'Полосатый', 'Пятнистый', 'Красноватый', 'Желтоватый', 'Голубоватый']
  }},
  { id: 'school', name: { az: 'Məktəb', tr: 'Okul', en: 'School', ru: 'Школа' }, icon: GraduationCap, color: 'from-violet-500 to-purple-500', words: {
      az: ['Qələm', 'Pozan', 'Xətkeş', 'Kitab', 'Lövhə', 'Parta', 'Stul', 'Müəllim', 'Şagird', 'Sinif', 'Məktəb', 'Direktor', 'Tənəffüs', 'Zəng', 'İmtahan', 'Qiymət', 'Gündəlik', 'Çanta', 'Dərs', 'Ev Tapşırığı', 'Riyaziyyat', 'Ana Dili', 'Tarix', 'Coğrafiya', 'Fizika', 'Kimya', 'Biologiya', 'İnformatika', 'İdman Dərsi', 'Rəsm', 'Musiqi', 'Ədəbiyyat', 'İngilis Dili', 'Rus Dili', 'Laboratoriya', 'Kitabxana', 'Bufet', 'Akt Zalı', 'Həyət', 'Forma', 'Qələmqabı', 'Marker', 'Təbaşir', 'Xəritə', 'Qlobus', 'Mikroskop', 'Kompüter', 'Proyektor', 'Diplom', 'Attestat'],
      tr: ['Kalem', 'Silgi', 'Cetvel', 'Kitap', 'Tahta', 'Sıra', 'Sandalye', 'Öğretmen', 'Öğrenci', 'Sınıf', 'Okul', 'Müdür', 'Teneffüs', 'Zil', 'Sınav', 'Not', 'Günlük', 'Çanta', 'Ders', 'Ödev', 'Matematik', 'Ana Dil', 'Tarih', 'Coğrafya', 'Fizik', 'Kimya', 'Biyoloji', 'Bilişim', 'Beden Eğitimi', 'Resim', 'Müzik', 'Edebiyat', 'İngilizce', 'Rusça', 'Laboratuvar', 'Kütüphane', 'Kantin', 'Konferans Salonu', 'Bahçe', 'Forma', 'Kalemlik', 'Keçeli Kalem', 'Tebeşir', 'Harita', 'Küre', 'Mikroskop', 'Bilgisayar', 'Projeksiyon', 'Diploma', 'Karne'],
      en: ['Pen', 'Eraser', 'Ruler', 'Book', 'Board', 'Desk', 'Chair', 'Teacher', 'Student', 'Classroom', 'School', 'Principal', 'Break', 'Bell', 'Exam', 'Grade', 'Diary', 'Bag', 'Lesson', 'Homework', 'Math', 'Native Language', 'History', 'Geography', 'Physics', 'Chemistry', 'Biology', 'IT', 'PE', 'Art', 'Music', 'Literature', 'English', 'Russian', 'Lab', 'Library', 'Cafeteria', 'Hall', 'Yard', 'Uniform', 'Pencil Case', 'Marker', 'Chalk', 'Map', 'Globe', 'Microscope', 'Computer', 'Projector', 'Diploma', 'Certificate'],
      ru: ['Ручка', 'Ластик', 'Линейка', 'Книга', 'Доска', 'Парта', 'Стул', 'Учитель', 'Ученик', 'Класс', 'Школа', 'Директор', 'Перемена', 'Звонок', 'Экзамен', 'Оценка', 'Дневник', 'Сумка', 'Урок', 'Домашнее Задание', 'Математика', 'Родной Язык', 'История', 'География', 'Физика', 'Химия', 'Биология', 'Информатика', 'Физкультура', 'ИЗО', 'Музыка', 'Литература', 'Английский', 'Русский', 'Лаборатория', 'Библиотека', 'Буфет', 'Актовый Зал', 'Двор', 'Форма', 'Пенал', 'Маркер', 'Мел', 'Карта', 'Глобус', 'Микроскоп', 'Компьютер', 'Проектор', 'Диплом', 'Аттестат']
   }},

  { id: 'cinema', name: { az: 'Kino', tr: 'Sinema', en: 'Cinema', ru: 'Кино' }, icon: Film, color: 'from-rose-500 to-pink-500', words: {
      az: ['Rejissor', 'Aktyor', 'Ssenari', 'Montaj', 'Efekt', 'Kamera', 'Dekor', 'Kostyum', 'Makyaj', 'Musiqi', 'Seans', 'Afişa', 'Treyler', 'Premyera', 'Festival', 'Oskar', 'Qızıl Kürə', 'Ssenari Müəllifi', 'Prodüser', 'Operator', 'Dublyaj', 'Altyazı', 'Animasiya', 'Sənədli Film', 'Komediya', 'Dram', 'Triller', 'Dəhşət', 'Fantastika', 'Ekran', 'Projetor', 'Bufet', 'Bilet', 'Sıra', 'Kreslo', 'Qaranlıq', 'Applodisment', 'Rol', 'Epizod', 'Serial'],
      tr: ['Yönetmen', 'Oyuncu', 'Senaryo', 'Kurgu', 'Efekt', 'Kamera', 'Dekor', 'Kostüm', 'Makyaj', 'Müzik', 'Seans', 'Afiş', 'Fragman', 'Gala', 'Festival', 'Oscar', 'Altın Küre', 'Senarist', 'Yapımcı', 'Görüntü Yönetmeni', 'Dublaj', 'Altyazı', 'Animasyon', 'Belgesel', 'Komedi', 'Drama', 'Gerilim', 'Korku', 'Bilim Kurgu', 'Perde', 'Projektör', 'Büfe', 'Bilet', 'Sıra', 'Koltuk', 'Karanlık', 'Alkış', 'Rol', 'Bölüm', 'Dizi'],
      en: ['Director', 'Actor', 'Script', 'Editing', 'Effect', 'Camera', 'Set', 'Costume', 'Makeup', 'Soundtrack', 'Screening', 'Poster', 'Trailer', 'Premiere', 'Festival', 'Oscar', 'Golden Globe', 'Screenwriter', 'Producer', 'Cinematographer', 'Dubbing', 'Subtitle', 'Animation', 'Documentary', 'Comedy', 'Drama', 'Thriller', 'Horror', 'Sci-Fi', 'Screen', 'Projector', 'Concession', 'Ticket', 'Row', 'Seat', 'Darkness', 'Applause', 'Role', 'Episode', 'Series'],
      ru: ['Режиссёр', 'Актёр', 'Сценарий', 'Монтаж', 'Эффект', 'Камера', 'Декорация', 'Костюм', 'Грим', 'Саундтрек', 'Сеанс', 'Афиша', 'Трейлер', 'Премьера', 'Фестиваль', 'Оскар', 'Золотой Глобус', 'Сценарист', 'Продюсер', 'Оператор', 'Дубляж', 'Субтитры', 'Анимация', 'Документальный', 'Комедия', 'Драма', 'Триллер', 'Ужасы', 'Фантастика', 'Экран', 'Проектор', 'Буфет', 'Билет', 'Ряд', 'Кресло', 'Темнота', 'Аплодисменты', 'Роль', 'Эпизод', 'Сериал']
  }},

  { id: 'history', name: { az: 'Tarix', tr: 'Tarih', en: 'History', ru: 'История' }, icon: Book, color: 'from-amber-600 to-yellow-500', words: {
      az: ['Fironlar', 'Piramida', 'Gladiator', 'Kolizey', 'Vikinglar', 'Şövalye', 'Qala', 'Kral', 'Kraliça', 'İmperator', 'Respublika', 'İnqilab', 'Müharibə', 'Sülh Müqaviləsi', 'Xəritə', 'Kəşfiyyat', 'Kolumb', 'Silk Yolu', 'Xilafət', 'Osmanlı', 'Səlib Yürüşü', 'Renessans', 'Sənaye İnqilabı', 'Fransız İnqilabı', 'Napoleon', 'Birinci Dünya Müharibəsi', 'İkinci Dünya Müharibəsi', 'Soyuq Müharibə', 'Berlin Divarı', 'Sovet İttifaqı', 'Müstəqillik', 'Konstitusiya', 'Parlament', 'Demokratiya', 'Monarxiya', 'Arxeologiya', 'Muzey', 'Artefakt', 'Sikkə', 'Yazı'],
      tr: ['Firavunlar', 'Piramit', 'Gladyatör', 'Kolezyum', 'Vikinglar', 'Şövalye', 'Kale', 'Kral', 'Kraliçe', 'İmparator', 'Cumhuriyet', 'Devrim', 'Savaş', 'Barış Antlaşması', 'Harita', 'Keşif', 'Kolomb', 'İpek Yolu', 'Halifelik', 'Osmanlı', 'Haçlı Seferi', 'Rönesans', 'Sanayi Devrimi', 'Fransız Devrimi', 'Napolyon', 'Birinci Dünya Savaşı', 'İkinci Dünya Savaşı', 'Soğuk Savaş', 'Berlin Duvarı', 'Sovyetler Birliği', 'Bağımsızlık', 'Anayasa', 'Meclis', 'Demokrasi', 'Monarşi', 'Arkeoloji', 'Müze', 'Eser', 'Sikke', 'Yazıt'],
      en: ['Pharaohs', 'Pyramid', 'Gladiator', 'Colosseum', 'Vikings', 'Knight', 'Castle', 'King', 'Queen', 'Emperor', 'Republic', 'Revolution', 'War', 'Peace Treaty', 'Map', 'Exploration', 'Columbus', 'Silk Road', 'Caliphate', 'Ottoman', 'Crusade', 'Renaissance', 'Industrial Revolution', 'French Revolution', 'Napoleon', 'World War I', 'World War II', 'Cold War', 'Berlin Wall', 'Soviet Union', 'Independence', 'Constitution', 'Parliament', 'Democracy', 'Monarchy', 'Archaeology', 'Museum', 'Artifact', 'Coin', 'Inscription'],
      ru: ['Фараоны', 'Пирамида', 'Гладиатор', 'Колизей', 'Викинги', 'Рыцарь', 'Замок', 'Король', 'Королева', 'Император', 'Республика', 'Революция', 'Война', 'Мирный договор', 'Карта', 'Открытие', 'Колумб', 'Шёлковый путь', 'Халифат', 'Османская', 'Крестовый поход', 'Ренессанс', 'Промышленная революция', 'Французская революция', 'Наполеон', 'Первая мировая', 'Вторая мировая', 'Холодная война', 'Берлинская стена', 'Советский Союз', 'Независимость', 'Конституция', 'Парламент', 'Демократия', 'Монархия', 'Археология', 'Музей', 'Артефакт', 'Монета', 'Надпись']
  }},

  { id: 'space', name: { az: 'Kosmos', tr: 'Uzay', en: 'Space', ru: 'Космос' }, icon: Star, color: 'from-indigo-600 to-violet-600', words: {
      az: ['Günəş', 'Ay', 'Mars', 'Venera', 'Yupiter', 'Saturn', 'Uran', 'Neptun', 'Pluton', 'Asteroid', 'Meteor', 'Kometa', 'Qalaktika', 'Kəhkəşan', 'Qara Dəlik', 'Ulduz', 'Supernova', 'Nebula', 'Kosmik Stansiya', 'Raket', 'Kosmik Gəmi', 'Astronavt', 'Teleskop', 'Peyk', 'Orbit', 'Cazibə', 'Vakuum', 'Işıq İli', 'Qırmızı Nöqtə', 'Günəş Sistemi', 'Ekzoplanet', 'Kosmik Toz', 'Qamma Şüalanması', 'Pulsarlar', 'Kvazar', 'Kosmik Şüa', 'Ay Gəzintisi', 'Sputnik', 'NASA', 'SpaceX'],
      tr: ['Güneş', 'Ay', 'Mars', 'Venüs', 'Jüpiter', 'Satürn', 'Uranüs', 'Neptün', 'Plüton', 'Asteroit', 'Meteor', 'Kuyruklu Yıldız', 'Galaksi', 'Samanyolu', 'Kara Delik', 'Yıldız', 'Süpernova', 'Nebula', 'Uzay İstasyonu', 'Roket', 'Uzay Gemisi', 'Astronot', 'Teleskop', 'Uydu', 'Yörünge', 'Yerçekimi', 'Vakum', 'Işık Yılı', 'Kırmızı Leke', 'Güneş Sistemi', 'Ekzogezegen', 'Kozmik Toz', 'Gama Işını', 'Pulsar', 'Kuasar', 'Kozmik Işın', 'Ay Yürüyüşü', 'Sputnik', 'NASA', 'SpaceX'],
      en: ['Sun', 'Moon', 'Mars', 'Venus', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'Pluto', 'Asteroid', 'Meteor', 'Comet', 'Galaxy', 'Milky Way', 'Black Hole', 'Star', 'Supernova', 'Nebula', 'Space Station', 'Rocket', 'Spacecraft', 'Astronaut', 'Telescope', 'Satellite', 'Orbit', 'Gravity', 'Vacuum', 'Light Year', 'Red Spot', 'Solar System', 'Exoplanet', 'Cosmic Dust', 'Gamma Ray', 'Pulsar', 'Quasar', 'Cosmic Ray', 'Moonwalk', 'Sputnik', 'NASA', 'SpaceX'],
      ru: ['Солнце', 'Луна', 'Марс', 'Венера', 'Юпитер', 'Сатурн', 'Уран', 'Нептун', 'Плутон', 'Астероид', 'Метеор', 'Комета', 'Галактика', 'Млечный Путь', 'Чёрная Дыра', 'Звезда', 'Сверхновая', 'Туманность', 'Космическая Станция', 'Ракета', 'Космический Корабль', 'Космонавт', 'Телескоп', 'Спутник', 'Орбита', 'Гравитация', 'Вакуум', 'Световой Год', 'Красное Пятно', 'Солнечная Система', 'Экзопланета', 'Космическая Пыль', 'Гамма-Луч', 'Пульсар', 'Квазар', 'Космический Луч', 'Лунная Прогулка', 'Спутник', 'НАСА', 'SpaceX']
  }},

  { id: 'technology', name: { az: 'Texnologiya', tr: 'Teknoloji', en: 'Technology', ru: 'Технологии' }, icon: Laptop, color: 'from-cyan-500 to-blue-500', words: {
      az: ['Süni İntellekt', 'Robot', 'Kompüter', 'Smartfon', 'Planşet', 'Noutbuk', 'Server', 'Bulud', 'Proqram', 'Tətbiq', 'Veb Sayt', 'İnternet', 'Wi-Fi', 'Bluetooth', 'USB', 'Çip', 'Prosessor', 'Yaddaş', 'Ekran', 'Klaviatura', 'Siçan', 'Printer', 'Skaner', 'Kamera', 'Dron', 'Virtual Reallıq', 'Artırılmış Reallıq', 'Blokçeyn', 'Kriptovalyuta', 'Kibertəhlükəsizlik', 'Verilənlər Bazası', 'Alqoritm', 'Kod', 'Proqramçı', 'Haker', 'Firewall', 'Şifrə', 'Sosial Şəbəkə', 'Streaming', 'Podcast'],
      tr: ['Yapay Zeka', 'Robot', 'Bilgisayar', 'Akıllı Telefon', 'Tablet', 'Dizüstü', 'Sunucu', 'Bulut', 'Yazılım', 'Uygulama', 'Web Sitesi', 'İnternet', 'Wi-Fi', 'Bluetooth', 'USB', 'Çip', 'İşlemci', 'Bellek', 'Ekran', 'Klavye', 'Fare', 'Yazıcı', 'Tarayıcı', 'Kamera', 'Drone', 'Sanal Gerçeklik', 'Artırılmış Gerçeklik', 'Blokzincir', 'Kripto Para', 'Siber Güvenlik', 'Veritabanı', 'Algoritma', 'Kod', 'Yazılımcı', 'Hacker', 'Güvenlik Duvarı', 'Şifre', 'Sosyal Medya', 'Yayın', 'Podcast'],
      en: ['Artificial Intelligence', 'Robot', 'Computer', 'Smartphone', 'Tablet', 'Laptop', 'Server', 'Cloud', 'Software', 'App', 'Website', 'Internet', 'Wi-Fi', 'Bluetooth', 'USB', 'Chip', 'Processor', 'Memory', 'Screen', 'Keyboard', 'Mouse', 'Printer', 'Scanner', 'Camera', 'Drone', 'Virtual Reality', 'Augmented Reality', 'Blockchain', 'Cryptocurrency', 'Cybersecurity', 'Database', 'Algorithm', 'Code', 'Developer', 'Hacker', 'Firewall', 'Password', 'Social Media', 'Streaming', 'Podcast'],
      ru: ['Искусственный Интеллект', 'Робот', 'Компьютер', 'Смартфон', 'Планшет', 'Ноутбук', 'Сервер', 'Облако', 'Программа', 'Приложение', 'Сайт', 'Интернет', 'Wi-Fi', 'Bluetooth', 'USB', 'Чип', 'Процессор', 'Память', 'Экран', 'Клавиатура', 'Мышь', 'Принтер', 'Сканер', 'Камера', 'Дрон', 'Виртуальная Реальность', 'Дополненная Реальность', 'Блокчейн', 'Криптовалюта', 'Кибербезопасность', 'База Данных', 'Алгоритм', 'Код', 'Разработчик', 'Хакер', 'Брандмауэр', 'Пароль', 'Соцсети', 'Стриминг', 'Подкаст']
  }},

  { id: 'nature', name: { az: 'Təbiət', tr: 'Doğa', en: 'Nature', ru: 'Природа' }, icon: Cloud, color: 'from-green-500 to-teal-500', words: {
      az: ['Meşə', 'Dağ', 'Çay', 'Göl', 'Okean', 'Şəlalə', 'Mağara', 'Vulkan', 'Zəlzələ', 'Sunami', 'Tufan', 'Qasırğa', 'Qar', 'Yağış', 'Dolu', 'Şimşək', 'Göy Gurultusu', 'Gökkuşağı', 'Günəş Batımı', 'Günəş Çıxımı', 'Ay Işığı', 'Ulduzlu Gecə', 'Çiçək', 'Ağac', 'Kök', 'Yarpaq', 'Budaq', 'Toxum', 'Bitki', 'Ot', 'Mamır', 'Göbələk', 'Qaya', 'Torpaq', 'Qum', 'Buz', 'Buzlaq', 'Səhra', 'Savanna', 'Cəngəllik'],
      tr: ['Orman', 'Dağ', 'Nehir', 'Göl', 'Okyanus', 'Şelale', 'Mağara', 'Yanardağ', 'Deprem', 'Tsunami', 'Fırtına', 'Kasırga', 'Kar', 'Yağmur', 'Dolu', 'Şimşek', 'Gök Gürültüsü', 'Gökkuşağı', 'Gün Batımı', 'Gün Doğumu', 'Ay Işığı', 'Yıldızlı Gece', 'Çiçek', 'Ağaç', 'Kök', 'Yaprak', 'Dal', 'Tohum', 'Bitki', 'Ot', 'Yosun', 'Mantar', 'Kaya', 'Toprak', 'Kum', 'Buz', 'Buzul', 'Çöl', 'Savan', 'Orman'],
      en: ['Forest', 'Mountain', 'River', 'Lake', 'Ocean', 'Waterfall', 'Cave', 'Volcano', 'Earthquake', 'Tsunami', 'Storm', 'Hurricane', 'Snow', 'Rain', 'Hail', 'Lightning', 'Thunder', 'Rainbow', 'Sunset', 'Sunrise', 'Moonlight', 'Starry Night', 'Flower', 'Tree', 'Root', 'Leaf', 'Branch', 'Seed', 'Plant', 'Grass', 'Moss', 'Mushroom', 'Rock', 'Soil', 'Sand', 'Ice', 'Glacier', 'Desert', 'Savanna', 'Jungle'],
      ru: ['Лес', 'Гора', 'Река', 'Озеро', 'Океан', 'Водопад', 'Пещера', 'Вулкан', 'Землетрясение', 'Цунами', 'Буря', 'Ураган', 'Снег', 'Дождь', 'Град', 'Молния', 'Гром', 'Радуга', 'Закат', 'Рассвет', 'Лунный Свет', 'Звёздная Ночь', 'Цветок', 'Дерево', 'Корень', 'Лист', 'Ветка', 'Семя', 'Растение', 'Трава', 'Мох', 'Гриб', 'Скала', 'Почва', 'Песок', 'Лёд', 'Ледник', 'Пустыня', 'Саванна', 'Джунгли']
  }},
];